version: '3'

services:
  janusgraph:
    image: docker.io/janusgraph/janusgraph:latest
    container_name: janusgraph-default
    ports:
      - "8182:8182"
    # The mounted volume only makes sense if JanusGraph is being run with the BerekeleyDB storage.
    volumes:
      - "janusgraph-default-data:/var/lib/janusgraph"
      - "./janusgraph-config:/etc/opt/janusgraph:ro"
      - "./janusgraph-config/net-spider-index.groovy:/docker-entrypoint-initdb.d/net-spider-index.groovy"
      
  # timescale:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.db 
  #   image: chopaan/timescale
  #   command: postgres -c shared_preload_libraries=timescaledb -c log_statement=all -c log_destination=stderr
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=chopaan
  #     - POSTGRES_PASSWORD=testPassword
  #     - PGPASSWORD=testPassword
  #   volumes:
  #     #- ./data:/var/lib/postgresql
  #     - ./db_migrations/1.psql:/docker-entrypoint-initdb.d/init.sql
  # chopaan:
  #   image: chopaan
  #   depends_on:
  #     - timescale
  #   restart: always
  #   ports:
  #     - 3000:3000
  #     - 8080:8080
  #     - 443:443
  #   volumes:
  #     - ~/.aws/credentials:/.aws/credentials
  #   links:
  #     - "timescale"
  #   #command: /opt/chopaan/chopaan

volumes:
  janusgraph-default-data:
