version: '3'
<<<<<<< HEAD

services:
  timescale:
    image: chopaan/timescale
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./data:/var/lib/postgresql
      - ./db_migrations/1.psql:/docker-entrypoint-initdb.d/init.sql
=======
services:
  chopaan:
    build:
      context: .
      args:
        - BINARY_PATH
    image: dosti/chopaan
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
    ports:
      - 3000:3000
    #command: /opt/chopaan/chopaan
>>>>>>> bd5e081... the required
