version: '3'

services:
  db:
    image: janusgraph/janusgraph:0.6.0
    container_name: janusgraph-default
    ports:
      - "8182:8182"
    # The mounted volume only makes sense if JanusGraph is being run with the BerekeleyDB storage.
    volumes:
      - "janusgraph-default-data:/var/lib/janusgraph"
      - "./janusgraph-config/config/:/etc/opt/janusgraph:ro"
      - "./janusgraph-config/indexes/net-spider-index.groovy:/files/net-spider-index.groovy"
  # server:
  #   depends_on:
  #     - db
  #   image: chopaan-server:latest
  #   container_name : server
  #   links:
  #     - db
  #   ports:
  #     - "8888:8888"
  # ui:
  #   depends_on:
  #     - server
  #   image: chopaan-ui:latest
  #   container_name : ui
  #   links:
  #     - server
  #   ports:
  #     - "8080:8080"
  # kbtzim:
  #   depends_on:
  #     - db
  #   image: chopaan-kbtzim:latest
  #   container_name : kbtzim
  #   links:
  #     - db

volumes:
  janusgraph-default-data:
