name:                chopaan
version:             0.1.0.0
github:              faezs/chopaan
license:             BSD3
author:              Faez Shakil
maintainer:          faez.shakil@gmail.com
copyright:           2019 Faez Shakil


extra-source-files:
- README.md
- ChangeLog.md

data-files:
 - options.dhall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/faezs/chopaan#readme>



dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- async
- exceptions
- deepseq
- ghc-prim
- unagi-chan
- aeson
- proto-lens
- proto-lens-runtime
- text
- bytestring
- data-default-class
- containers
- unordered-containers
- stm
- time
- time-compat >= 1.9.2.2
- ulid
- directory
- microlens
- streamly >= 0.7.2
- mtl
- transformers
- resourcet
- hashable
- estimator
- cassava
- distributive
- linear
- ad
- dhall <= 1.33.0
- keys
- vector
- vector-sized
- dimensional
- retry
- algebraic-graphs >= 0.5
- katip
- resource-pool
- monad-bayes
- base64-bytestring
- servant
- servant-js
- sbv
- diagrams-lib
- diagrams-svg >= 1.4.3
- diagrams-contrib >= 1.4.4
- SVGFonts
- comonad
- pointed
- interpolatedstring-perl6
- blaze-markup
- servant-blaze
- retry
- Shpadoinkle >= 0.3.0.0
- Shpadoinkle-backend-pardiff
- Shpadoinkle-html
- Shpadoinkle-widgets
- Shpadoinkle-router
- Shpadoinkle-lens
- jsaddle
- ghcjs-dom
- newtype-generics
- lens
- raw-strings-qq
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple
- concat-classes
- concat-examples
- concat-plugin
- network-uri
- network
- websockets
- servant-server
- servant-websockets
- amazonka
- amazonka-iot
- amazonka-s3
- net-mqtt >= 0.7.0
- wai
- warp
- connection
- conduit
- tls
- x509-store
- x509-validation
- net-spider
- greskell
- greskell-core
- suavemente
- compensated

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src
  ghc-options:
    - -fplugin=ConCat.Plugin

executables:
  server:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - chopaan
    - optparse-simple
    - base
    other-modules:
    - Paths_chopaan
    ghc-options:
      - -threaded
      - -O2
      - -eventlog
      - -fplugin=ConCat.Plugin

tests:
  chopaan-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - chopaan
    - hspec
    - QuickCheck
    - checkers
    - proto-lens-arbitrary
    - quickspec
    - quickcheck-instances
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
