name:                chopaan
version:             0.1.0.0
github:              faezs/chopaan
license:             BSD3
author:              Faez Shakil
maintainer:          faez.shakil@gmail.com
copyright:           2019 Faez Shakil

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

build-tools:
  proto-lens-protoc:proto-lens-protoc

extra-source-files:
- README.md
- ChangeLog.md
- node_message_schema/NodeMessages.proto

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/faezs/chopaan#readme>




dependencies:
- base >= 4.11 && < 10
- proto-lens-runtime
- rio >= 0.1.8.0
- amazonka
- amazonka-iot
- net-mqtt
- aeson
- proto-lens
- text
- bytestring
- connection
- tls
- x509-store
- x509-validation
- data-default-class
- network-uri
- containers
- unordered-containers
- stm
- time
- ulid
- convertible
- time-lens
- brick
- vty
- directory
- microlens
- streamly
- mtl
- vector
- microlens-th
- stm-containers
- hashable
- kalman
- hmatrix
- estimator
- cassava
- streamly-cassava
- streamly-bytestring
- compensated
- distributive
- linear
- ad
- numeric-limits
- dhall >= 1.24.0
- total-map
- keys
- concat-classes
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  generated-exposed-modules:
    - Proto.NodeMessages
    - Proto.NodeMessages_Fields


executables:
  chopaan-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - chopaan
    - optparse-simple
    - base
    other-modules:
    - Paths_chopaan
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  chopaan-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - chopaan
    - hspec
    - QuickCheck
    - checkers
    - proto-lens-arbitrary
    - quickcheck-instances
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
