name:                chopaan
version:             0.1.0.0
github:              faezs/chopaan
license:             BSD3
author:              Faez Shakil
maintainer:          faez.shakil@gmail.com
copyright:           2019 Faez Shakil


extra-source-files:
- README.md
- ChangeLog.md

data-files:
 - options.dhall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/faezs/chopaan#readme>



dependencies:
- base >= 4.11 && < 10
- proto-lens-runtime
- proto-lens-protoc
- rio >= 0.1.8.0
- exceptions
- amazonka
- amazonka-iot
- amazonka-s3
- conduit
- net-mqtt >= 0.7.0
- unagi-chan
- aeson
- proto-lens
- text
- bytestring
- connection
- tls
- x509-store
- x509-validation
- data-default-class
- network-uri
- containers
- unordered-containers
- stm
- time
- time-compat >= 1.9.2.2
- ulid
- convertible
- time-lens
- directory
- microlens
- generic-lens
- streamly >= 0.7.2
- mtl
- transformers
- resourcet
- hashable
- hmatrix
- estimator
- cassava
- compensated
- distributive
- linear
- ad
- numeric-limits
- dhall
- keys
- vector
- vector-sized
- dimensional
- retry
- algebraic-graphs
- katip
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple
- postgresql-libpq
- resource-pool
- concat-classes
- concat-examples
- concat-plugin
- monad-bayes
- ghc-prim
- base64-bytestring
- wai
- warp
- websockets
- servant
- servant-server
- servant-websockets
- servant-js
- sbv
- suavemente
- diagrams-lib
- diagrams-svg >= 1.4.2
- diagrams-contrib >= 1.4.4
- ekg
- ekg-core
- comonad
- pointed
- interpolatedstring-perl6
- blaze-markup
- servant-blaze
- retry
- Shpadoinkle >= 0.3.0.0
- Shpadoinkle-backend-pardiff
- Shpadoinkle-html
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=ConCat.Plugin
- -O2

library:
  source-dirs: src


executables:
  chopaan-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - chopaan
    - optparse-simple
    - base
    other-modules:
    - Paths_chopaan
    ghc-options:
      - -threaded
      - -eventlog
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
  tx-test-exe:
    main:                Tx.hs
    source-dirs:         app
    dependencies:
    - chopaan
    - optparse-simple
    - base
    other-modules:
    - Paths_chopaan
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=ConCat.Plugin
    - -O2
    
tests:
  chopaan-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - chopaan
    - hspec
    - QuickCheck
    - checkers
    - proto-lens-arbitrary
    - quickcheck-instances
    - quickspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=ConCat.Plugin
    - -O2
