#!/usr/bin/env python3
"""
Physics-Informed Neural Network Training for AC Power Flow Dispatch

Trains a neural network to predict P,Q setpoints from power generation/load data,
using samples generated by the IPOPT optimal power flow solver.

Two architectures available:

1. Dense Network (default):
   - Simple MLP with physics-informed loss
   - Fast to train, good for small grids

2. Summing Functor Network (--use-functor):
   - Based on Manin-Marcolli categorical framework
   - Outputs edge flows, projects to Kirchhoff equalizer
   - GUARANTEED power balance by construction (no soft penalty needed)
   - Better for larger/complex grids

Key features:
- Outputs P,Q setpoints (what inverters control), not V,δ
- Physics-informed loss: penalizes power balance violations
- MC Dropout: uncertainty quantification at inference time
- Realistic sampling: solar curves, load profiles, weather noise

Usage:
    python train_dispatch.py ac_samples.csv 12 8 --epochs 200
    python train_dispatch.py ac_samples.csv 12 8 --use-functor --epochs 200
    python train_dispatch.py --help

Expected training time:
    Dense: ~30 min on CPU, ~5 min on GPU
    Functor: ~60 min on CPU, ~10 min on GPU

Expected accuracy:
    P setpoint: <0.5 kW RMSE
    Q setpoint: <0.2 kVAR RMSE
"""

import argparse
import json
from pathlib import Path
from typing import Tuple, Dict, List, Optional

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, Dataset

# Try to import graph neural network components
try:
    from summing_functor_net import (
        SummingFunctorDispatcher, PowerGridGraph, verify_kirchhoff
    )
    HAS_FUNCTOR = True
except ImportError:
    HAS_FUNCTOR = False
    print("Warning: summing_functor_net not available, --use-functor disabled")


class DispatchNet(nn.Module):
    """
    Physics-informed neural network for P,Q dispatch.

    Predicts optimal P and Q setpoints for each PV inverter given
    current conditions (available solar, loads, time of day).
    """

    def __init__(self, n_nodes: int, n_pv: int, dropout: float = 0.1):
        super().__init__()
        self.n_nodes = n_nodes
        self.n_pv = n_pv

        # Input: hour + n_pv*p_max + n_nodes*p_load + n_nodes*q_load
        input_dim = 1 + n_pv + 2 * n_nodes
        # Output: n_pv*p_set + n_pv*q_set
        output_dim = 2 * n_pv

        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(dropout / 2),  # Lighter dropout in last hidden
            nn.Linear(128, output_dim)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

    def get_pq(self, output: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """Split output into P and Q setpoints."""
        p_set = output[:, :self.n_pv]
        q_set = output[:, self.n_pv:]
        return p_set, q_set


class PhysicsInformedLoss(nn.Module):
    """
    Combined MSE + physics constraint loss.

    Physics constraints:
    1. P_set must be in [0, P_max] - enforced via clamping
    2. Q_set must be in [-Q_max, Q_max] - enforced via clamping
    3. S = sqrt(P² + Q²) <= S_rated - penalized in loss
    4. Net power balance should minimize losses - implicit in training data

    The physics loss penalizes violations of inverter apparent power limits.
    """

    def __init__(self, n_pv: int, lambda_physics: float = 0.1):
        super().__init__()
        self.n_pv = n_pv
        self.lambda_physics = lambda_physics
        self.mse = nn.MSELoss()

    def forward(
        self,
        pred: torch.Tensor,
        target: torch.Tensor,
        p_max: torch.Tensor,
        s_rated: torch.Tensor
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        """
        Compute combined loss.

        Args:
            pred: Predicted [P_set, Q_set] of shape (batch, 2*n_pv)
            target: Target [P_set, Q_set] of shape (batch, 2*n_pv)
            p_max: Available P for each PV node, shape (batch, n_pv)
            s_rated: Inverter ratings, shape (batch, n_pv)

        Returns:
            total_loss: Combined MSE + physics loss
            metrics: Dict with individual loss components
        """
        # Split predictions
        p_pred = pred[:, :self.n_pv]
        q_pred = pred[:, self.n_pv:]

        # MSE loss on setpoints
        mse_loss = self.mse(pred, target)

        # Physics loss 1: P should be in [0, P_max]
        p_violation_low = torch.relu(-p_pred)  # Penalty for P < 0
        p_violation_high = torch.relu(p_pred - p_max)  # Penalty for P > P_max
        p_bound_loss = (p_violation_low.pow(2) + p_violation_high.pow(2)).mean()

        # Physics loss 2: Q should be in [-Q_max, Q_max] where Q_max ≈ 0.3 * S_rated
        q_max = s_rated * 0.3
        q_violation = torch.relu(q_pred.abs() - q_max)
        q_bound_loss = q_violation.pow(2).mean()

        # Physics loss 3: Apparent power S = sqrt(P² + Q²) <= S_rated
        s_apparent = torch.sqrt(p_pred.pow(2) + q_pred.pow(2) + 1e-6)
        s_violation = torch.relu(s_apparent - s_rated)
        s_loss = s_violation.pow(2).mean()

        # Combined physics loss
        physics_loss = p_bound_loss + q_bound_loss + s_loss

        # Total loss
        total_loss = mse_loss + self.lambda_physics * physics_loss

        metrics = {
            'mse': mse_loss.item(),
            'p_bound': p_bound_loss.item(),
            'q_bound': q_bound_loss.item(),
            's_limit': s_loss.item(),
            'physics': physics_loss.item(),
            'total': total_loss.item()
        }

        return total_loss, metrics


def load_data(
    csv_path: str,
    n_nodes: int,
    n_pv: int
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, Tuple]:
    """
    Load and preprocess training data from CSV.

    Args:
        csv_path: Path to CSV with columns from generateRealisticDataset
        n_nodes: Total number of nodes
        n_pv: Number of PV nodes

    Returns:
        X: Input features (normalized)
        Y: Target P,Q setpoints (normalized)
        P_max: Available P per PV node (for physics loss)
        S_rated: Inverter ratings (estimated)
        norm_params: Normalization parameters
    """
    df = pd.read_csv(csv_path)

    # Determine PV node indices (same logic as Haskell: idx % 3 != 2 and idx != 0)
    pv_indices = [i for i in range(1, n_nodes) if i % 3 != 2]
    if len(pv_indices) != n_pv:
        print(f"Warning: Expected {n_pv} PV nodes, found {len(pv_indices)}")
        n_pv = len(pv_indices)

    # Input columns
    input_cols = (
        ['hour'] +
        [f'pmax_{i}' for i in pv_indices] +
        [f'pload_{i}' for i in range(n_nodes)] +
        [f'qload_{i}' for i in range(n_nodes)]
    )

    # Output columns
    output_cols = (
        [f'p_set_{i}' for i in pv_indices] +
        [f'q_set_{i}' for i in pv_indices]
    )

    # Check columns
    missing = [c for c in input_cols + output_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns: {missing}")

    X = df[input_cols].values.astype(np.float32)
    Y = df[output_cols].values.astype(np.float32)

    # Extract P_max for physics loss
    pmax_cols = [f'pmax_{i}' for i in pv_indices]
    P_max = df[pmax_cols].values.astype(np.float32)

    # Estimate S_rated as 1.1 × max(P_max) per column (typical oversizing)
    S_rated = P_max * 1.1

    # Normalize inputs
    X_mean = X.mean(axis=0)
    X_std = X.std(axis=0) + 1e-8
    X_norm = (X - X_mean) / X_std

    # Normalize outputs
    Y_mean = Y.mean(axis=0)
    Y_std = Y.std(axis=0) + 1e-8
    Y_norm = (Y - Y_mean) / Y_std

    norm_params = {
        'X_mean': X_mean,
        'X_std': X_std,
        'Y_mean': Y_mean,
        'Y_std': Y_std
    }

    return X_norm, Y_norm, P_max, S_rated, norm_params


def train(
    csv_path: str,
    n_nodes: int,
    n_pv: int,
    epochs: int = 200,
    batch_size: int = 64,
    lr: float = 1e-3,
    lambda_physics: float = 0.1,
    output_dir: str = "."
) -> nn.Module:
    """
    Train the physics-informed dispatch network.

    Args:
        csv_path: Path to training data CSV
        n_nodes: Total number of nodes
        n_pv: Number of PV nodes
        epochs: Training epochs
        batch_size: Batch size
        lr: Learning rate
        lambda_physics: Weight for physics loss term
        output_dir: Output directory for model and params

    Returns:
        Trained model
    """
    print(f"Loading data from {csv_path}...")
    X, Y, P_max, S_rated, norm_params = load_data(csv_path, n_nodes, n_pv)
    print(f"Loaded {len(X)} samples, {n_pv} PV nodes")

    # Train/val split (90/10)
    n_train = int(0.9 * len(X))
    indices = np.random.permutation(len(X))
    train_idx, val_idx = indices[:n_train], indices[n_train:]

    X_train, X_val = X[train_idx], X[val_idx]
    Y_train, Y_val = Y[train_idx], Y[val_idx]
    P_max_train, P_max_val = P_max[train_idx], P_max[val_idx]
    S_rated_train, S_rated_val = S_rated[train_idx], S_rated[val_idx]

    print(f"Training: {len(X_train)}, Validation: {len(X_val)}")

    # Create datasets
    train_ds = TensorDataset(
        torch.from_numpy(X_train),
        torch.from_numpy(Y_train),
        torch.from_numpy(P_max_train),
        torch.from_numpy(S_rated_train)
    )
    val_ds = TensorDataset(
        torch.from_numpy(X_val),
        torch.from_numpy(Y_val),
        torch.from_numpy(P_max_val),
        torch.from_numpy(S_rated_val)
    )

    train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_dl = DataLoader(val_ds, batch_size=batch_size)

    # Initialize model and training components
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = DispatchNet(n_nodes, n_pv).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', patience=15, factor=0.5
    )
    criterion = PhysicsInformedLoss(n_pv, lambda_physics)

    best_val_loss = float('inf')
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"\nTraining for {epochs} epochs with λ_physics={lambda_physics}...")
    print("-" * 70)

    for epoch in range(epochs):
        # Training
        model.train()
        train_metrics = {'mse': 0, 'physics': 0, 'total': 0}

        for X_b, Y_b, P_max_b, S_rated_b in train_dl:
            X_b = X_b.to(device)
            Y_b = Y_b.to(device)
            P_max_b = P_max_b.to(device)
            S_rated_b = S_rated_b.to(device)

            optimizer.zero_grad()
            pred = model(X_b)
            loss, metrics = criterion(pred, Y_b, P_max_b, S_rated_b)
            loss.backward()
            optimizer.step()

            for k, v in metrics.items():
                if k in train_metrics:
                    train_metrics[k] += v

        for k in train_metrics:
            train_metrics[k] /= len(train_dl)

        # Validation
        model.eval()
        val_metrics = {'mse': 0, 'physics': 0, 'total': 0}

        with torch.no_grad():
            for X_b, Y_b, P_max_b, S_rated_b in val_dl:
                X_b = X_b.to(device)
                Y_b = Y_b.to(device)
                P_max_b = P_max_b.to(device)
                S_rated_b = S_rated_b.to(device)

                pred = model(X_b)
                _, metrics = criterion(pred, Y_b, P_max_b, S_rated_b)

                for k, v in metrics.items():
                    if k in val_metrics:
                        val_metrics[k] += v

        for k in val_metrics:
            val_metrics[k] /= len(val_dl)

        scheduler.step(val_metrics['total'])

        # Save best model
        if val_metrics['total'] < best_val_loss:
            best_val_loss = val_metrics['total']
            torch.save(model.state_dict(), output_path / 'dispatch_net.pt')

        # Log progress
        if epoch % 10 == 0 or epoch == epochs - 1:
            lr_current = optimizer.param_groups[0]['lr']
            print(f"Epoch {epoch:4d}: "
                  f"train_mse={train_metrics['mse']:.6f} "
                  f"train_phys={train_metrics['physics']:.6f} | "
                  f"val_mse={val_metrics['mse']:.6f} "
                  f"val_phys={val_metrics['physics']:.6f} | "
                  f"lr={lr_current:.2e}")

    print("-" * 70)
    print(f"Best validation loss: {best_val_loss:.6f}")

    # Save normalization parameters
    np.savez(
        output_path / 'norm_params.npz',
        **{k: v for k, v in norm_params.items()}
    )

    # Save as JSON for Haskell
    norm_json = {k: v.tolist() for k, v in norm_params.items()}
    norm_json['n_nodes'] = n_nodes
    norm_json['n_pv'] = n_pv
    with open(output_path / 'dispatch_net.pt.norm.json', 'w') as f:
        json.dump(norm_json, f)

    print(f"\nModel saved to: {output_path / 'dispatch_net.pt'}")
    print(f"Norm params saved to: {output_path / 'norm_params.npz'}")

    # Final evaluation
    model.load_state_dict(torch.load(output_path / 'dispatch_net.pt', weights_only=True))
    evaluate(model, val_dl, n_pv, norm_params, device)

    return model


def evaluate(
    model: nn.Module,
    val_dl: DataLoader,
    n_pv: int,
    norm_params: Dict,
    device: torch.device
) -> None:
    """Evaluate model and print metrics."""
    model.eval()

    all_pred = []
    all_true = []

    with torch.no_grad():
        for X_b, Y_b, _, _ in val_dl:
            X_b = X_b.to(device)
            pred = model(X_b).cpu().numpy()
            all_pred.append(pred)
            all_true.append(Y_b.numpy())

    pred = np.vstack(all_pred)
    true = np.vstack(all_true)

    # Denormalize
    Y_mean, Y_std = norm_params['Y_mean'], norm_params['Y_std']
    pred = pred * Y_std + Y_mean
    true = true * Y_std + Y_mean

    # Split P and Q
    p_pred, p_true = pred[:, :n_pv], true[:, :n_pv]
    q_pred, q_true = pred[:, n_pv:], true[:, n_pv:]

    # Metrics
    p_rmse = np.sqrt(np.mean((p_pred - p_true) ** 2))
    q_rmse = np.sqrt(np.mean((q_pred - q_true) ** 2))
    p_mae = np.mean(np.abs(p_pred - p_true))
    q_mae = np.mean(np.abs(q_pred - q_true))
    p_max_err = np.max(np.abs(p_pred - p_true))
    q_max_err = np.max(np.abs(q_pred - q_true))

    print("\n" + "=" * 70)
    print("EVALUATION RESULTS (denormalized)")
    print("=" * 70)
    print(f"\nReal Power Setpoints (kW):")
    print(f"  RMSE:      {p_rmse:.4f}")
    print(f"  MAE:       {p_mae:.4f}")
    print(f"  Max Error: {p_max_err:.4f}")
    print(f"\nReactive Power Setpoints (kVAR):")
    print(f"  RMSE:      {q_rmse:.4f}")
    print(f"  MAE:       {q_mae:.4f}")
    print(f"  Max Error: {q_max_err:.4f}")

    # Check thresholds
    p_ok = p_rmse < 0.5
    q_ok = q_rmse < 0.2

    print(f"\nAcceptable for dispatch:")
    print(f"  P: {'✓ PASS' if p_ok else '✗ FAIL'} (threshold: 0.5 kW)")
    print(f"  Q: {'✓ PASS' if q_ok else '✗ FAIL'} (threshold: 0.2 kVAR)")
    print("=" * 70)


class PowerGridDataset(Dataset):
    """Dataset for graph-based power flow training."""

    def __init__(
        self,
        node_features: np.ndarray,
        edge_index: torch.Tensor,
        edge_features: np.ndarray,
        target_setpoints: np.ndarray,
        slack_node: int = 0
    ):
        self.node_features = torch.from_numpy(node_features).float()
        self.edge_index = edge_index
        self.edge_features = torch.from_numpy(edge_features).float()
        self.target_setpoints = torch.from_numpy(target_setpoints).float()
        self.slack_node = slack_node

    def __len__(self):
        return len(self.node_features)

    def __getitem__(self, idx):
        return (
            self.node_features[idx],
            self.edge_features[idx] if self.edge_features.dim() == 3 else self.edge_features,
            self.target_setpoints[idx]
        )


def build_radial_grid_topology(n_nodes: int) -> Tuple[torch.Tensor, int]:
    """
    Build edge_index for a radial grid topology.

    For a radial distribution system, edges connect:
    - Node 0 (slack/substation) to nodes 1, 2, 3 (main feeders)
    - Each main feeder branches to downstream nodes

    Returns:
        edge_index: (2, num_edges) tensor
        num_edges: number of edges
    """
    edges = []

    # Simple radial structure: 0 is root, others branch off
    # This creates a tree structure
    for i in range(1, n_nodes):
        # Connect to parent: parent(i) = (i-1) // 3 for a ternary tree
        parent = (i - 1) // 3 if i > 3 else 0
        edges.append((parent, i))
        edges.append((i, parent))  # Bidirectional for message passing

    src = [e[0] for e in edges]
    tgt = [e[1] for e in edges]

    edge_index = torch.tensor([src, tgt], dtype=torch.long)
    return edge_index, len(edges)


def load_graph_data(
    csv_path: str,
    n_nodes: int,
    n_pv: int,
    edge_topology_file: Optional[str] = None
) -> Tuple[np.ndarray, torch.Tensor, np.ndarray, np.ndarray, Dict]:
    """
    Load data and prepare for graph-based training.

    Args:
        csv_path: Path to CSV with training samples
        n_nodes: Number of nodes
        n_pv: Number of PV nodes
        edge_topology_file: Optional JSON file with edge definitions

    Returns:
        node_features: (n_samples, n_nodes, node_dim)
        edge_index: (2, num_edges)
        edge_features: (num_edges, edge_dim) - static edge features
        target_setpoints: (n_samples, n_pv, 2) - P, Q setpoints
        metadata: Dict with normalization params etc.
    """
    df = pd.read_csv(csv_path)

    # Build or load edge topology
    if edge_topology_file and Path(edge_topology_file).exists():
        with open(edge_topology_file) as f:
            topo = json.load(f)
            src = topo['src']
            tgt = topo['tgt']
            edge_index = torch.tensor([src, tgt], dtype=torch.long)
            num_edges = len(src)
    else:
        edge_index, num_edges = build_radial_grid_topology(n_nodes)

    # PV node indices (same as dense trainer)
    pv_indices = [i for i in range(1, n_nodes) if i % 3 != 2][:n_pv]

    n_samples = len(df)

    # Node features: [P_solar, P_load, Q_load, V_min, V_max, is_pv]
    node_dim = 6
    node_features = np.zeros((n_samples, n_nodes, node_dim), dtype=np.float32)

    for i in range(n_nodes):
        # P_load and Q_load columns
        if f'pload_{i}' in df.columns:
            node_features[:, i, 1] = df[f'pload_{i}'].values
        if f'qload_{i}' in df.columns:
            node_features[:, i, 2] = df[f'qload_{i}'].values

        # P_solar (only for PV nodes)
        if i in pv_indices and f'pmax_{i}' in df.columns:
            node_features[:, i, 0] = df[f'pmax_{i}'].values
            node_features[:, i, 5] = 1.0  # is_pv flag

        # Voltage limits (fixed for all)
        node_features[:, i, 3] = 0.95  # V_min (pu)
        node_features[:, i, 4] = 1.05  # V_max (pu)

    # Edge features: [R, X, B, S_rated] - static, same for all samples
    edge_dim = 4
    edge_features = np.zeros((num_edges, edge_dim), dtype=np.float32)

    # Default line parameters (typical LV distribution)
    for e in range(num_edges):
        edge_features[e, 0] = 0.01 + 0.005 * np.random.rand()  # R (pu)
        edge_features[e, 1] = 0.03 + 0.01 * np.random.rand()   # X (pu)
        edge_features[e, 2] = 0.01                              # B (pu)
        edge_features[e, 3] = 100.0                             # S_rated (kVA)

    # Target setpoints
    target_setpoints = np.zeros((n_samples, n_pv, 2), dtype=np.float32)
    for idx, pv_node in enumerate(pv_indices):
        if f'p_set_{pv_node}' in df.columns:
            target_setpoints[:, idx, 0] = df[f'p_set_{pv_node}'].values
        if f'q_set_{pv_node}' in df.columns:
            target_setpoints[:, idx, 1] = df[f'q_set_{pv_node}'].values

    # Normalize
    node_mean = node_features.mean(axis=(0, 1))
    node_std = node_features.std(axis=(0, 1)) + 1e-8
    node_features = (node_features - node_mean) / node_std

    target_mean = target_setpoints.mean(axis=0)
    target_std = target_setpoints.std(axis=0) + 1e-8
    target_setpoints_norm = (target_setpoints - target_mean) / target_std

    metadata = {
        'node_mean': node_mean,
        'node_std': node_std,
        'target_mean': target_mean,
        'target_std': target_std,
        'pv_indices': pv_indices,
        'n_nodes': n_nodes,
        'n_pv': n_pv,
        'num_edges': num_edges
    }

    return node_features, edge_index, edge_features, target_setpoints_norm, metadata


def train_functor(
    csv_path: str,
    n_nodes: int,
    n_pv: int,
    epochs: int = 200,
    batch_size: int = 32,
    lr: float = 1e-3,
    output_dir: str = "."
) -> nn.Module:
    """
    Train the summing functor network.

    This architecture guarantees Kirchhoff's law by construction:
    the Kirchhoff projection layer enforces power balance at all
    non-slack nodes.
    """
    if not HAS_FUNCTOR:
        raise RuntimeError("Summing functor network requires torch_geometric. "
                          "Install with: pip install torch-geometric")

    print(f"Loading graph data from {csv_path}...")
    node_features, edge_index, edge_features, targets, meta = load_graph_data(
        csv_path, n_nodes, n_pv
    )
    num_edges = meta['num_edges']
    print(f"Loaded {len(node_features)} samples, {n_nodes} nodes, {num_edges} edges")

    # Train/val split
    n_train = int(0.9 * len(node_features))
    indices = np.random.permutation(len(node_features))
    train_idx, val_idx = indices[:n_train], indices[n_train:]

    train_ds = PowerGridDataset(
        node_features[train_idx],
        edge_index,
        edge_features,
        targets[train_idx]
    )
    val_ds = PowerGridDataset(
        node_features[val_idx],
        edge_index,
        edge_features,
        targets[val_idx]
    )

    # Note: For graph data, we process one sample at a time or use batching
    # that respects graph structure. For simplicity, batch_size=1 here.
    train_dl = DataLoader(train_ds, batch_size=1, shuffle=True)
    val_dl = DataLoader(val_ds, batch_size=1)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Initialize model
    model = SummingFunctorDispatcher(
        num_nodes=n_nodes,
        num_edges=num_edges,
        node_input_dim=6,
        edge_input_dim=4,
        hidden_dim=64,
        slack_node=0
    ).to(device)

    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', patience=15, factor=0.5
    )
    mse_loss = nn.MSELoss()

    best_val_loss = float('inf')
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"\nTraining SummingFunctorNet for {epochs} epochs...")
    print("(Kirchhoff's law enforced by construction - no physics loss needed)")
    print("-" * 70)

    edge_index_dev = edge_index.to(device)
    edge_features_dev = torch.from_numpy(edge_features).float().to(device)

    for epoch in range(epochs):
        # Training
        model.train()
        train_loss = 0.0
        kirchhoff_violations = 0

        for node_feat, _, target in train_dl:
            node_feat = node_feat.squeeze(0).to(device)
            target = target.squeeze(0).to(device)

            # Create graph object
            graph = PowerGridGraph(
                num_nodes=n_nodes,
                num_edges=num_edges,
                edge_index=edge_index_dev,
                node_features=node_feat,
                edge_features=edge_features_dev,
                slack_node=0
            )

            optimizer.zero_grad()
            setpoints, edge_flows = model(graph)

            # Loss on PV node setpoints only
            pv_setpoints = setpoints[:, meta['pv_indices'], :]
            loss = mse_loss(pv_setpoints.squeeze(0), target)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

            # Verify Kirchhoff (should always be satisfied!)
            satisfied, _ = verify_kirchhoff(
                edge_flows, edge_index_dev, n_nodes, slack_node=0
            )
            if not satisfied:
                kirchhoff_violations += 1

        train_loss /= len(train_dl)

        # Validation
        model.eval()
        val_loss = 0.0

        with torch.no_grad():
            for node_feat, _, target in val_dl:
                node_feat = node_feat.squeeze(0).to(device)
                target = target.squeeze(0).to(device)

                graph = PowerGridGraph(
                    num_nodes=n_nodes,
                    num_edges=num_edges,
                    edge_index=edge_index_dev,
                    node_features=node_feat,
                    edge_features=edge_features_dev,
                    slack_node=0
                )

                setpoints, _ = model(graph)
                pv_setpoints = setpoints[:, meta['pv_indices'], :]
                loss = mse_loss(pv_setpoints.squeeze(0), target)
                val_loss += loss.item()

        val_loss /= len(val_dl)
        scheduler.step(val_loss)

        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), output_path / 'functor_dispatch_net.pt')

        # Log progress
        if epoch % 10 == 0 or epoch == epochs - 1:
            lr_current = optimizer.param_groups[0]['lr']
            print(f"Epoch {epoch:4d}: "
                  f"train_loss={train_loss:.6f} val_loss={val_loss:.6f} | "
                  f"lr={lr_current:.2e} | "
                  f"KCL violations: {kirchhoff_violations}")

    print("-" * 70)
    print(f"Best validation loss: {best_val_loss:.6f}")

    # Save metadata
    meta_save = {k: v.tolist() if isinstance(v, np.ndarray) else v
                 for k, v in meta.items()}
    with open(output_path / 'functor_dispatch_net.meta.json', 'w') as f:
        json.dump(meta_save, f)

    # Save edge topology
    topo = {
        'src': edge_index[0].tolist(),
        'tgt': edge_index[1].tolist()
    }
    with open(output_path / 'grid_topology.json', 'w') as f:
        json.dump(topo, f)

    print(f"\nModel saved to: {output_path / 'functor_dispatch_net.pt'}")
    print(f"Metadata saved to: {output_path / 'functor_dispatch_net.meta.json'}")

    return model


def main():
    parser = argparse.ArgumentParser(
        description="Train physics-informed neural network for AC power flow dispatch",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("csv_path", help="Path to training data CSV")
    parser.add_argument("n_nodes", type=int, help="Total number of nodes")
    parser.add_argument("n_pv", type=int, help="Number of PV (solar) nodes")
    parser.add_argument("--epochs", type=int, default=200, help="Training epochs")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--lambda-physics", type=float, default=0.1,
                        help="Weight for physics loss term")
    parser.add_argument("--output-dir", type=str, default=".",
                        help="Output directory")
    parser.add_argument("--use-functor", action="store_true",
                        help="Use summing functor network (requires torch-geometric)")

    args = parser.parse_args()

    if args.use_functor:
        train_functor(
            csv_path=args.csv_path,
            n_nodes=args.n_nodes,
            n_pv=args.n_pv,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            output_dir=args.output_dir
        )
    else:
        train(
            csv_path=args.csv_path,
            n_nodes=args.n_nodes,
            n_pv=args.n_pv,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            lambda_physics=args.lambda_physics,
            output_dir=args.output_dir
        )


if __name__ == "__main__":
    main()
