#!/usr/bin/env python3
"""
Neural Network Training Script for AC Power Flow Dispatch

Trains a neural network to predict voltage magnitudes and phase angles
from power generation/load data, using samples generated by the exact
SBV/dReal solver.

Architecture:
  Input(2N) → Dense(256) → ReLU → Dropout(0.1)
           → Dense(256) → ReLU → Dropout(0.1)
           → Dense(128) → ReLU
           → Output(2N-2)

Where N is the number of nodes, and we exclude the slack node from outputs.

Usage:
    python train_dispatch.py ac_samples.csv 12
    python train_dispatch.py --help

Expected training time:
    ~30 min on CPU
    ~5 min on GPU

Expected accuracy:
    <1% voltage error
    <2° angle error
"""

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset


class DispatchNet(nn.Module):
    """
    Neural network for AC power flow dispatch.

    Maps power generation and load to voltage magnitudes and phase angles.
    """

    def __init__(self, n_nodes: int):
        super().__init__()
        self.n_nodes = n_nodes
        self.net = nn.Sequential(
            nn.Linear(2 * n_nodes, 256),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(256, 256),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 2 * (n_nodes - 1))  # V and δ for non-slack nodes
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


def load_data(csv_path: str, n_nodes: int) -> tuple:
    """
    Load and preprocess training data from CSV.

    Args:
        csv_path: Path to CSV file with columns:
            sample_id, pgen_0..pgen_N, pload_0..pload_N, v_0..v_N, delta_0..delta_N
        n_nodes: Number of nodes in the network

    Returns:
        X: Input features (normalized)
        Y: Output targets (normalized)
        norm_params: Tuple of (input_mean, input_std) for denormalization
    """
    df = pd.read_csv(csv_path)

    # Input: P_gen and P_load for all nodes
    input_cols = [f'pgen_{i}' for i in range(n_nodes)] + \
                 [f'pload_{i}' for i in range(n_nodes)]

    # Output: V and δ for non-slack nodes (node 0 is slack)
    output_cols = [f'v_{i}' for i in range(1, n_nodes)] + \
                  [f'delta_{i}' for i in range(1, n_nodes)]

    # Check columns exist
    missing_input = [c for c in input_cols if c not in df.columns]
    missing_output = [c for c in output_cols if c not in df.columns]

    if missing_input:
        raise ValueError(f"Missing input columns: {missing_input}")
    if missing_output:
        raise ValueError(f"Missing output columns: {missing_output}")

    X = df[input_cols].values.astype(np.float32)
    Y = df[output_cols].values.astype(np.float32)

    # Normalize inputs to zero mean, unit variance
    X_mean, X_std = X.mean(axis=0), X.std(axis=0) + 1e-8
    X = (X - X_mean) / X_std

    # Normalize outputs:
    # V: center around 220V, scale by 50V (typical range 170-270)
    # δ: scale by 0.52 rad (~30°, typical range ±30°)
    n_v = n_nodes - 1  # Number of voltage outputs
    Y[:, :n_v] = (Y[:, :n_v] - 220) / 50
    Y[:, n_v:] = Y[:, n_v:] / 0.52

    return X, Y, (X_mean, X_std)


def train(
    csv_path: str,
    n_nodes: int,
    epochs: int = 200,
    batch_size: int = 64,
    lr: float = 1e-3,
    output_dir: str = "."
) -> nn.Module:
    """
    Train the dispatch network.

    Args:
        csv_path: Path to training data CSV
        n_nodes: Number of nodes in the network
        epochs: Number of training epochs
        batch_size: Batch size for training
        lr: Learning rate
        output_dir: Directory for output files

    Returns:
        Trained model
    """
    print(f"Loading data from {csv_path}...")
    X, Y, norm_params = load_data(csv_path, n_nodes)
    print(f"Loaded {len(X)} samples")

    # Train/validation split (90/10)
    n_train = int(0.9 * len(X))
    X_train, X_val = X[:n_train], X[n_train:]
    Y_train, Y_val = Y[:n_train], Y[n_train:]

    print(f"Training set: {len(X_train)} samples")
    print(f"Validation set: {len(X_val)} samples")

    # Create data loaders
    train_ds = TensorDataset(
        torch.from_numpy(X_train),
        torch.from_numpy(Y_train)
    )
    val_ds = TensorDataset(
        torch.from_numpy(X_val),
        torch.from_numpy(Y_val)
    )

    train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_dl = DataLoader(val_ds, batch_size=batch_size)

    # Initialize model
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = DispatchNet(n_nodes).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', patience=10, factor=0.5
    )
    criterion = nn.MSELoss()

    best_val_loss = float('inf')
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"\nTraining for {epochs} epochs...")
    print("-" * 60)

    for epoch in range(epochs):
        # Training phase
        model.train()
        train_loss = 0.0
        for X_batch, Y_batch in train_dl:
            X_batch, Y_batch = X_batch.to(device), Y_batch.to(device)

            optimizer.zero_grad()
            pred = model(X_batch)
            loss = criterion(pred, Y_batch)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        train_loss /= len(train_dl)

        # Validation phase
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for X_batch, Y_batch in val_dl:
                X_batch, Y_batch = X_batch.to(device), Y_batch.to(device)
                pred = model(X_batch)
                val_loss += criterion(pred, Y_batch).item()

        val_loss /= len(val_dl)
        scheduler.step(val_loss)

        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(
                model.state_dict(),
                output_path / 'dispatch_net.pt'
            )

        # Log progress
        if epoch % 10 == 0 or epoch == epochs - 1:
            current_lr = optimizer.param_groups[0]['lr']
            print(f"Epoch {epoch:4d}: train={train_loss:.6f}, "
                  f"val={val_loss:.6f}, lr={current_lr:.2e}")

    print("-" * 60)
    print(f"Best validation loss: {best_val_loss:.6f}")

    # Save normalization parameters
    np.savez(
        output_path / 'norm_params.npz',
        mean=norm_params[0],
        std=norm_params[1]
    )

    # Also save as JSON for Haskell consumption
    norm_json = {
        "npInputMean": norm_params[0].tolist(),
        "npInputStd": norm_params[1].tolist()
    }
    with open(output_path / 'dispatch_net.pt.norm.json', 'w') as f:
        json.dump(norm_json, f)

    print(f"\nModel saved to: {output_path / 'dispatch_net.pt'}")
    print(f"Norm params saved to: {output_path / 'norm_params.npz'}")
    print(f"Norm params (JSON) saved to: {output_path / 'dispatch_net.pt.norm.json'}")

    # Evaluate final model
    model.load_state_dict(torch.load(output_path / 'dispatch_net.pt', weights_only=True))
    evaluate(model, val_dl, n_nodes, device)

    return model


def evaluate(
    model: nn.Module,
    val_dl: DataLoader,
    n_nodes: int,
    device: torch.device
) -> None:
    """
    Evaluate model and print metrics.
    """
    model.eval()

    all_pred = []
    all_true = []

    with torch.no_grad():
        for X_batch, Y_batch in val_dl:
            X_batch = X_batch.to(device)
            pred = model(X_batch).cpu().numpy()
            all_pred.append(pred)
            all_true.append(Y_batch.numpy())

    pred = np.vstack(all_pred)
    true = np.vstack(all_true)

    n_v = n_nodes - 1  # Number of voltage outputs

    # Denormalize for physical interpretation
    pred_v = pred[:, :n_v] * 50 + 220
    pred_d = pred[:, n_v:] * 0.52
    true_v = true[:, :n_v] * 50 + 220
    true_d = true[:, n_v:] * 0.52

    # Compute errors
    v_rmse = np.sqrt(np.mean((pred_v - true_v) ** 2))
    d_rmse = np.sqrt(np.mean((pred_d - true_d) ** 2))
    d_rmse_deg = np.degrees(d_rmse)

    v_mae = np.mean(np.abs(pred_v - true_v))
    d_mae = np.mean(np.abs(pred_d - true_d))
    d_mae_deg = np.degrees(d_mae)

    v_max_err = np.max(np.abs(pred_v - true_v))
    d_max_err = np.max(np.abs(pred_d - true_d))
    d_max_err_deg = np.degrees(d_max_err)

    print("\n" + "=" * 60)
    print("EVALUATION RESULTS")
    print("=" * 60)
    print(f"\nVoltage (V):")
    print(f"  RMSE:      {v_rmse:.4f} V")
    print(f"  MAE:       {v_mae:.4f} V")
    print(f"  Max Error: {v_max_err:.4f} V")
    print(f"\nPhase Angle:")
    print(f"  RMSE:      {d_rmse:.6f} rad ({d_rmse_deg:.4f}°)")
    print(f"  MAE:       {d_mae:.6f} rad ({d_mae_deg:.4f}°)")
    print(f"  Max Error: {d_max_err:.6f} rad ({d_max_err_deg:.4f}°)")

    # Check against thresholds
    v_ok = v_rmse < 2.0  # < 2V
    d_ok = d_rmse_deg < 2.0  # < 2°

    print(f"\nAcceptable for dispatch:")
    print(f"  Voltage: {'✓ PASS' if v_ok else '✗ FAIL'} (threshold: 2V)")
    print(f"  Angle:   {'✓ PASS' if d_ok else '✗ FAIL'} (threshold: 2°)")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Train neural network for AC power flow dispatch",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        "csv_path",
        help="Path to training data CSV"
    )
    parser.add_argument(
        "n_nodes",
        type=int,
        help="Number of nodes in the network"
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=200,
        help="Number of training epochs"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=64,
        help="Batch size for training"
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=".",
        help="Directory for output files"
    )

    args = parser.parse_args()

    train(
        csv_path=args.csv_path,
        n_nodes=args.n_nodes,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        output_dir=args.output_dir
    )


if __name__ == "__main__":
    main()
