cabal-version: 2.4
name: mgenv-gen9
version: 0.1.0.0
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules:
      Physics.Units
    , Physics.Transmission
    , Physics.PV
    , Physics.Consumption
    , Physics.Storage
    , Geometry.EMST
    , Prob.Randomizable
    , Grid.HH
    , Grid.Sample
  build-depends:
      base
    , monad-bayes
    , containers
    , algebraic-graphs
  default-language: Haskell2010
  ghc-options: -Wno-all
