/*
Version 1 Schema
*/

CREATE ROLE chopaan WITH LOGIN PASSWORD '$PGPASSWORD' CREATEDB;

CREATE database chopaan;

GRANT ALL PRIVILEGES ON DATABASE chopaan TO chopaan;

/* Timescale initialization */
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE TABLE "users" (
       id        SERIAL      PRIMARY KEY,
       name      TEXT        NOT NULL,
       phone     TEXT        NOT NULL,
       createdAt TIMESTAMPTZ NOT NULL,
       updatedAt TIMESTAMPTZ NOT NULL
);

/* Node Config Table */
CREATE TABLE "nodes" (
       id              SERIAL   PRIMARY KEY,
       macaddr         MACADDR  NOT NULL,
       batteryType     TEXT     NOT NULL,
       batteryMinV     FLOAT    NOT NULL,
       batteryMaxV     FLOAT    NOT NULL,
       batteryAmpHours FLOAT    NOT NULL,
       pvOCV           FLOAT    NOT NULL,
       pvMPPTv         FLOAT    NOT NULL,
       pvMPPTi         FLOAT    NOT NULL,
       pvPower         FLOAT    NOT NULL,
       createdAt       TIMESTAMPTZ NOT NULL,
       updatedAt       TIMESTAMPTZ NOT NULL
);



/* Sensors Table */
CREATE TABLE "sensors" (
       node_id                INTEGER       REFERENCES nodes (id), 
       node_time              TIMESTAMPTZ   NOT NULL,
       battey_voltage         FLOAT         NOT NULL,
       grid_voltage           FLOAT         NOT NULL,
       solar_voltage          FLOAT         NOT NULL,
       load_battery_current   FLOAT         NOT NULL,
       grid_battery_current   FLOAT         NOT NULL,
       grid_relay_current     FLOAT         NOT NULL,
       generation_current     FLOAT         NOT NULL,
       temperature            FLOAT         NOT NULL,
       PRIMARY KEY(node_time, node_id)
);

/* create a hypertable */
SELECT create_hypertable('sensors', 'node_time');


/* Kibbutz Table */
CREATE TABLE "kibbutzim" (
       id        SERIAL      NOT NULL,
       name      TEXT        NOT NULL,
       nodes     INTEGER[]   NOT NULL, -- references nodes (id)
       chopaans  INTEGER[]   NOT NULL, -- references users (id)
       createdAt TIMESTAMPTZ NOT NULL,
       updatedAt TIMESTAMPTZ NOT NULL
);

CREATE TABLE "sessions" (
       node_id           INTEGER       REFERENCES nodes (id),
       session_start     TIMESTAMPTZ   NOT NULL,
       session_end       TIMESTAMPTZ   NOT NULL,
       energy_tx_in      FLOAT         NOT NULL,
       energy_tx_out     FLOAT         NOT NULL,
       energy_consumed   FLOAT         NOT NULL,
       energy_generated  FLOAT         NOT NULL,

       PRIMARY KEY(session_start, node_id)
);

SELECT create_hypertable('sessions', 'session_start');


CREATE TABLE "transactions" (
       transaction_id     SERIAL,
       transaction_ulid   TEXT               NOT NULL,
       start_time         TIMESTAMPTZ        NOT NULL,
       end_time           TIMESTAMPTZ        NOT NULL,
       nodes              INTEGER[]          NOT NULL,
       powers             FLOAT[]            NOT NULL,
       cost_per_watt      FLOAT[]            NOT NULL,

       PRIMARY KEY(transaction_id, start_time)
);

SELECT create_hypertable('transactions', 'start_time');
