{-# LANGUAGE CPP #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}

-- | Neural Network Dispatcher for Real-Time AC Power Flow
--
-- Provides fast (~1ms) inference for real-time dispatch decisions,
-- trained on samples generated by the exact SBV/dReal solver.
--
-- Architecture:
--
-- @
-- Input (2N):                    Output (2N-2):
-- ┌─────────────────────┐        ┌─────────────────────┐
-- │ P_gen_0 ... P_gen_N │        │ V_1 ... V_N         │
-- │ P_load_0...P_load_N │   ──▶  │ δ_1 ... δ_N         │
-- └─────────────────────┘        └─────────────────────┘
--                                (slack node excluded)
--
-- Hidden layers:
--   Input(2N) → Dense(256) → ReLU → Dropout(0.1)
--            → Dense(256) → ReLU → Dropout(0.1)
--            → Dense(128) → ReLU
--            → Output(2N-2)
-- @

module Chopaan.AC.NeuralDispatch
  ( -- * Types
    DispatchNet(..)
  , DispatchResult(..)
  , NormParams(..)
    -- * Network Operations
  , loadNet
  , dispatch
  , dispatchBatch
    -- * Validation
  , validateDispatch
  , ValidationResult(..)
  ) where

#ifndef ghcjs_HOST_OS

import qualified Data.Map.Strict as Map
import Data.Aeson
import GHC.Generics
import qualified Data.ByteString.Lazy.Char8 as BL
import System.Process (readProcess)
import Control.DeepSeq (NFData)
import Control.Exception (try, SomeException)
import Data.Text (Text)
import qualified Data.Text as T

import Chopaan.AC.Solver (ACProblem(..), ACSolution(..), NodeState(..), solveACPowerFlow)

-- | Dispatch result from neural network inference
data DispatchResult = DispatchResult
  { drVoltages   :: [Double]      -- ^ V_1 ... V_N (non-slack nodes)
  , drAngles     :: [Double]      -- ^ δ_1 ... δ_N (non-slack nodes)
  , drConfidence :: Double        -- ^ Model confidence (0-1)
  } deriving (Show, Eq, Generic, NFData, FromJSON, ToJSON)

-- | Normalization parameters from training
data NormParams = NormParams
  { npInputMean :: [Double]
  , npInputStd  :: [Double]
  } deriving (Show, Eq, Generic, NFData, FromJSON, ToJSON)

-- | Neural network handle (wraps Python subprocess or ONNX runtime)
data DispatchNet = DispatchNet
  { dnModelPath  :: FilePath
  , dnNormParams :: Maybe NormParams
  , dnNumNodes   :: Int
  } deriving (Show, Eq, Generic, NFData)

-- | Load trained model from disk
loadNet :: FilePath    -- ^ Path to model weights (.pt file)
        -> Int         -- ^ Number of nodes in network
        -> IO DispatchNet
loadNet modelPath nNodes = do
  -- Optionally load normalization params
  let normPath = modelPath ++ ".norm.json"
  normParams <- try (BL.readFile normPath) >>= \case
    Left (_ :: SomeException) -> return Nothing
    Right bs -> return $ decode bs

  return DispatchNet
    { dnModelPath = modelPath
    , dnNormParams = normParams
    , dnNumNodes = nNodes
    }

-- | Run inference for a single set of inputs
--
-- Expected latency: ~1ms
dispatch :: DispatchNet
         -> [Double]     -- ^ P_gen for each node
         -> [Double]     -- ^ P_load for each node
         -> IO DispatchResult
dispatch DispatchNet{..} pGen pLoad = do
  let input = object
        [ "model_path" .= dnModelPath
        , "p_gen" .= pGen
        , "p_load" .= pLoad
        , "n_nodes" .= dnNumNodes
        ]

  output <- readProcess "python3" ["-c", inferenceScript] (BL.unpack $ encode input)

  case decode (BL.pack output) of
    Just result -> return result
    Nothing -> error $ "Neural network inference failed: " ++ output

-- | Run batch inference for multiple inputs
dispatchBatch :: DispatchNet
              -> [([Double], [Double])]  -- ^ List of (P_gen, P_load) pairs
              -> IO [DispatchResult]
dispatchBatch net inputs = mapM (uncurry (dispatch net)) inputs

-- | Python script for PyTorch inference
inferenceScript :: String
inferenceScript = unlines
  [ "import sys, json"
  , "import torch"
  , "import torch.nn as nn"
  , ""
  , "class DispatchNet(nn.Module):"
  , "    def __init__(self, n_nodes):"
  , "        super().__init__()"
  , "        self.net = nn.Sequential("
  , "            nn.Linear(2 * n_nodes, 256),"
  , "            nn.ReLU(),"
  , "            nn.Dropout(0.1),"
  , "            nn.Linear(256, 256),"
  , "            nn.ReLU(),"
  , "            nn.Dropout(0.1),"
  , "            nn.Linear(256, 128),"
  , "            nn.ReLU(),"
  , "            nn.Linear(128, 2 * (n_nodes - 1))  # V and delta for non-slack"
  , "        )"
  , "    "
  , "    def forward(self, x):"
  , "        return self.net(x)"
  , ""
  , "inp = json.loads(sys.stdin.read())"
  , "model_path = inp['model_path']"
  , "p_gen = inp['p_gen']"
  , "p_load = inp['p_load']"
  , "n_nodes = inp.get('n_nodes', len(p_gen))"
  , ""
  , "model = DispatchNet(n_nodes)"
  , "model.load_state_dict(torch.load(model_path, map_location='cpu', weights_only=True))"
  , "model.eval()"
  , ""
  , "x = torch.tensor(p_gen + p_load, dtype=torch.float32).unsqueeze(0)"
  , "with torch.no_grad():"
  , "    y = model(x).squeeze(0).numpy()"
  , ""
  , "n = n_nodes - 1"
  , "voltages = y[:n].tolist()"
  , "angles = y[n:].tolist()"
  , ""
  , "# Denormalize and clamp to physical bounds"
  , "# V: centered at 220V with 50V scale, clamp to [160, 270]"
  , "# delta: scaled by 0.52 rad (30 deg), clamp to [-0.52, 0.52]"
  , "voltages = [max(160.0, min(270.0, 220.0 + v * 50.0)) for v in voltages]"
  , "angles = [max(-0.52, min(0.52, a * 0.52)) for a in angles]"
  , ""
  , "result = {"
  , "    'drVoltages': voltages,"
  , "    'drAngles': angles,"
  , "    'drConfidence': 0.95  # placeholder, could be computed from model uncertainty"
  , "}"
  , "print(json.dumps(result))"
  ]

-- | Validation result from comparing neural net to exact solver
data ValidationResult = ValidationResult
  { vrAcceptable    :: Bool    -- ^ Within acceptable error bounds
  , vrVoltageRMSE   :: Double  -- ^ Voltage RMSE (V)
  , vrAngleRMSE     :: Double  -- ^ Angle RMSE (rad)
  , vrTotalError    :: Double  -- ^ Combined error metric
  } deriving (Show, Eq, Generic, NFData, ToJSON, FromJSON)

-- | Validate dispatch result against exact solver (async in production)
--
-- Acceptable if: V error < 2V, δ error < 0.01 rad (~0.6°)
validateDispatch :: ACProblem -> DispatchResult -> IO ValidationResult
validateDispatch prob result = do
  exactSol <- solveACPowerFlow prob
  case exactSol of
    Nothing -> return ValidationResult
      { vrAcceptable = False
      , vrVoltageRMSE = 1e6
      , vrAngleRMSE = 1e6
      , vrTotalError = 1e6
      }
    Just sol -> do
      let exactV = [v | (_, (v, _)) <- drop 1 $ Map.toList (solVoltages sol)]  -- Skip slack
          exactD = [d | (_, (_, d)) <- drop 1 $ Map.toList (solVoltages sol)]
          predV = drVoltages result
          predD = drAngles result

          -- RMSE calculations
          vError = sqrt $ mean [(v1-v2)^(2::Int) | (v1,v2) <- zip exactV predV]
          dError = sqrt $ mean [(d1-d2)^(2::Int) | (d1,d2) <- zip exactD predD]

          -- Acceptable if V within 2V, δ within 0.01 rad
          acceptable = vError < 2.0 && dError < 0.01

      return ValidationResult
        { vrAcceptable = acceptable
        , vrVoltageRMSE = vError
        , vrAngleRMSE = dError
        , vrTotalError = vError + dError * 100  -- Weight angle errors
        }
  where
    mean :: [Double] -> Double
    mean [] = 0
    mean xs = sum xs / fromIntegral (length xs)

#else

-- GHCJS stub - Neural dispatch requires native Python subprocess
import GHC.Generics
import Data.Aeson
import Control.DeepSeq (NFData)

data DispatchResult = DispatchResult
  { drVoltages :: [Double]
  , drAngles :: [Double]
  , drConfidence :: Double
  } deriving (Show, Eq, Generic, NFData, FromJSON, ToJSON)

data NormParams = NormParams
  { npInputMean :: [Double]
  , npInputStd :: [Double]
  } deriving (Show, Eq, Generic, NFData, FromJSON, ToJSON)

data DispatchNet = DispatchNet
  { dnModelPath :: FilePath
  , dnNormParams :: Maybe NormParams
  , dnNumNodes :: Int
  } deriving (Show, Eq, Generic, NFData)

data ValidationResult = ValidationResult
  { vrAcceptable :: Bool
  , vrVoltageRMSE :: Double
  , vrAngleRMSE :: Double
  , vrTotalError :: Double
  } deriving (Show, Eq, Generic, NFData, ToJSON, FromJSON)

loadNet :: FilePath -> Int -> IO DispatchNet
loadNet _ _ = error "Neural dispatch not available in GHCJS"

dispatch :: DispatchNet -> [Double] -> [Double] -> IO DispatchResult
dispatch _ _ _ = error "Neural dispatch not available in GHCJS"

dispatchBatch :: DispatchNet -> [([Double], [Double])] -> IO [DispatchResult]
dispatchBatch _ _ = error "Neural dispatch not available in GHCJS"

validateDispatch :: a -> DispatchResult -> IO ValidationResult
validateDispatch _ _ = error "Neural dispatch not available in GHCJS"

#endif
