{-# LANGUAGE CPP #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}
{-# LANGUAGE LambdaCase #-}

-- | Neural Network Dispatcher for Real-Time AC Power Flow
--
-- Provides fast (~1-5ms) inference for real-time P,Q dispatch decisions,
-- trained on samples generated by the IPOPT optimal power flow solver.
--
-- Key features:
--   * Outputs P,Q setpoints (not V,δ) — what inverters actually control
--   * MC Dropout for uncertainty quantification
--   * Physics-informed loss during training
--   * Persistent Python subprocess for low-latency inference
--
-- Architecture:
--
-- @
-- Input:                           Output:
-- ┌─────────────────────────┐      ┌─────────────────────────┐
-- │ hour                    │      │ P_set_1 ... P_set_N     │
-- │ P_max_1 ... P_max_N     │  ──▶ │ Q_set_1 ... Q_set_N     │
-- │ P_load_0 ... P_load_N   │      │ uncertainty             │
-- │ Q_load_0 ... Q_load_N   │      └─────────────────────────┘
-- └─────────────────────────┘
--
-- Hidden layers (with dropout kept at inference for MC Dropout):
--   Input → Dense(256) → ReLU → Dropout(0.1)
--        → Dense(256) → ReLU → Dropout(0.1)
--        → Dense(128) → ReLU → Dropout(0.05)
--        → Output
-- @

module Chopaan.AC.NeuralDispatch
  ( -- * Types
    DispatchNet(..)
  , DispatchResult(..)
  , InferenceServer(..)
    -- * Server Lifecycle
  , startInferenceServer
  , stopInferenceServer
  , withInferenceServer
    -- * Inference
  , dispatch
  , dispatchWithUncertainty
    -- * Validation
  , validateDispatch
  , ValidationResult(..)
  ) where

#ifndef ghcjs_HOST_OS

import qualified Data.Map.Strict as Map
import Data.Aeson
import GHC.Generics
import qualified Data.ByteString.Lazy.Char8 as BL
import qualified Data.ByteString.Char8 as BS
import Control.DeepSeq (NFData)
import Control.Exception (try, SomeException, bracket, finally)
import Control.Concurrent (threadDelay)
import Control.Concurrent.MVar
import System.Process
import System.IO
import Network.Socket hiding (send, recv)
import Network.Socket.ByteString (send, recv)
import Data.IORef
import Text.Printf (printf)

import Chopaan.AC.Solver

-- | Dispatch result from neural network inference
data DispatchResult = DispatchResult
  { drPSetpoints  :: Map.Map String Double  -- ^ P setpoint per PV node (kW)
  , drQSetpoints  :: Map.Map String Double  -- ^ Q setpoint per PV node (kVAR)
  , drUncertainty :: Double                 -- ^ Uncertainty estimate (std dev of MC samples)
  , drConfidence  :: Double                 -- ^ Confidence (1 - normalized uncertainty)
  } deriving (Show, Eq, Generic, NFData, FromJSON, ToJSON)

-- | Neural network configuration
data DispatchNet = DispatchNet
  { dnModelPath   :: FilePath
  , dnNumNodes    :: Int
  , dnNumPVNodes  :: Int
  , dnMCSamples   :: Int       -- ^ Number of MC Dropout samples for uncertainty
  } deriving (Show, Eq, Generic, NFData)

-- | Persistent Python inference server (socket-based for low latency)
data InferenceServer = InferenceServer
  { isProcess    :: ProcessHandle
  , isSocket     :: Socket
  , isLock       :: MVar ()           -- ^ Serialize requests
  , isConfig     :: DispatchNet
  }

-- | Start the inference server (persistent Python process)
--
-- Uses Unix domain socket for ~1ms round-trip instead of ~100ms subprocess spawn
startInferenceServer :: DispatchNet -> IO InferenceServer
startInferenceServer config@DispatchNet{..} = do
  -- Create Unix socket
  let socketPath = "/tmp/chopaan_dispatch_" ++ show dnNumNodes ++ ".sock"

  -- Remove stale socket if exists
  _ <- try (removeFile socketPath) :: IO (Either SomeException ())

  -- Start Python server process
  (_, _, _, ph) <- createProcess (proc "python3" ["-c", serverScript, dnModelPath, show dnNumNodes, show dnNumPVNodes, show dnMCSamples, socketPath])
    { std_out = CreatePipe
    , std_err = CreatePipe
    }

  -- Wait for server to start
  threadDelay 500000  -- 500ms

  -- Connect to server
  sock <- socket AF_UNIX Stream 0
  connect sock (SockAddrUnix socketPath)

  lock <- newMVar ()

  return InferenceServer
    { isProcess = ph
    , isSocket = sock
    , isLock = lock
    , isConfig = config
    }

-- | Stop the inference server
stopInferenceServer :: InferenceServer -> IO ()
stopInferenceServer InferenceServer{..} = do
  -- Send shutdown command
  _ <- try (send isSocket "SHUTDOWN\n") :: IO (Either SomeException Int)
  close isSocket
  terminateProcess isProcess
  _ <- waitForProcess isProcess
  return ()

-- | Bracket for server lifecycle
withInferenceServer :: DispatchNet -> (InferenceServer -> IO a) -> IO a
withInferenceServer config = bracket (startInferenceServer config) stopInferenceServer

-- | Run inference (single forward pass, no uncertainty)
dispatch :: InferenceServer
         -> Double       -- ^ Hour of day
         -> [Double]     -- ^ P_max for each PV node
         -> [Double]     -- ^ P_load for each node
         -> [Double]     -- ^ Q_load for each node
         -> IO DispatchResult
dispatch server hour pMax pLoad qLoad = do
  result <- dispatchWithUncertainty server hour pMax pLoad qLoad False
  return result { drUncertainty = 0, drConfidence = 1.0 }

-- | Run inference with MC Dropout uncertainty estimation
--
-- Runs multiple forward passes with dropout enabled, returns mean and std
dispatchWithUncertainty :: InferenceServer
                        -> Double       -- ^ Hour of day
                        -> [Double]     -- ^ P_max for each PV node
                        -> [Double]     -- ^ P_load for each node
                        -> [Double]     -- ^ Q_load for each node
                        -> Bool         -- ^ Enable MC Dropout
                        -> IO DispatchResult
dispatchWithUncertainty InferenceServer{..} hour pMax pLoad qLoad mcDropout = do
  let request = object
        [ "hour" .= hour
        , "p_max" .= pMax
        , "p_load" .= pLoad
        , "q_load" .= qLoad
        , "mc_dropout" .= mcDropout
        , "mc_samples" .= dnMCSamples isConfig
        ]

  -- Serialize access to socket
  takeMVar isLock
  result <- finally (do
    -- Send request
    let msg = BL.toStrict (encode request) <> "\n"
    _ <- send isSocket msg

    -- Receive response
    response <- recv isSocket 65536
    return $ decode (BL.fromStrict response)
    ) (putMVar isLock ())

  case result of
    Just r -> return r
    Nothing -> error "Inference server returned invalid response"

-- | Python inference server script
serverScript :: String
serverScript = unlines
  [ "import sys, json, os, socket"
  , "import torch"
  , "import torch.nn as nn"
  , "import numpy as np"
  , ""
  , "class DispatchNet(nn.Module):"
  , "    '''Neural network for P,Q dispatch with MC Dropout.'''"
  , "    def __init__(self, n_nodes, n_pv):"
  , "        super().__init__()"
  , "        # Input: hour + n_pv*p_max + n_nodes*p_load + n_nodes*q_load"
  , "        input_dim = 1 + n_pv + 2 * n_nodes"
  , "        # Output: n_pv*p_set + n_pv*q_set"
  , "        output_dim = 2 * n_pv"
  , ""
  , "        self.net = nn.Sequential("
  , "            nn.Linear(input_dim, 256),"
  , "            nn.ReLU(),"
  , "            nn.Dropout(0.1),"
  , "            nn.Linear(256, 256),"
  , "            nn.ReLU(),"
  , "            nn.Dropout(0.1),"
  , "            nn.Linear(256, 128),"
  , "            nn.ReLU(),"
  , "            nn.Dropout(0.05),"
  , "            nn.Linear(128, output_dim)"
  , "        )"
  , "        self.n_pv = n_pv"
  , ""
  , "    def forward(self, x):"
  , "        return self.net(x)"
  , ""
  , "def main():"
  , "    model_path = sys.argv[1]"
  , "    n_nodes = int(sys.argv[2])"
  , "    n_pv = int(sys.argv[3])"
  , "    mc_samples = int(sys.argv[4])"
  , "    socket_path = sys.argv[5]"
  , ""
  , "    # Load model"
  , "    model = DispatchNet(n_nodes, n_pv)"
  , "    if os.path.exists(model_path):"
  , "        model.load_state_dict(torch.load(model_path, map_location='cpu', weights_only=True))"
  , "    model.eval()  # Base eval mode (dropout disabled unless we enable it)"
  , ""
  , "    # Create Unix socket server"
  , "    if os.path.exists(socket_path):"
  , "        os.remove(socket_path)"
  , "    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)"
  , "    server.bind(socket_path)"
  , "    server.listen(1)"
  , ""
  , "    conn, _ = server.accept()"
  , ""
  , "    while True:"
  , "        try:"
  , "            data = conn.recv(65536).decode().strip()"
  , "            if not data or data == 'SHUTDOWN':"
  , "                break"
  , ""
  , "            req = json.loads(data)"
  , "            hour = req['hour']"
  , "            p_max = req['p_max']"
  , "            p_load = req['p_load']"
  , "            q_load = req['q_load']"
  , "            do_mc = req.get('mc_dropout', False)"
  , "            n_mc = req.get('mc_samples', mc_samples)"
  , ""
  , "            # Build input tensor"
  , "            x = torch.tensor([hour] + p_max + p_load + q_load, dtype=torch.float32).unsqueeze(0)"
  , ""
  , "            if do_mc:"
  , "                # MC Dropout: run multiple passes with dropout enabled"
  , "                model.train()  # Enable dropout"
  , "                samples = []"
  , "                with torch.no_grad():"
  , "                    for _ in range(n_mc):"
  , "                        y = model(x).squeeze(0).numpy()"
  , "                        samples.append(y)"
  , "                model.eval()"
  , ""
  , "                samples = np.array(samples)"
  , "                y_mean = samples.mean(axis=0)"
  , "                y_std = samples.std(axis=0)"
  , "                uncertainty = float(y_std.mean())"
  , "            else:"
  , "                with torch.no_grad():"
  , "                    y_mean = model(x).squeeze(0).numpy()"
  , "                uncertainty = 0.0"
  , ""
  , "            # Split into P and Q setpoints"
  , "            p_set = y_mean[:n_pv].tolist()"
  , "            q_set = y_mean[n_pv:].tolist()"
  , ""
  , "            # Clamp P to [0, p_max], Q to [-q_max, q_max]"
  , "            p_set = [max(0, min(pm, p)) for p, pm in zip(p_set, p_max)]"
  , "            q_max_approx = [pm * 0.3 for pm in p_max]  # 30% Q capability"
  , "            q_set = [max(-qm, min(qm, q)) for q, qm in zip(q_set, q_max_approx)]"
  , ""
  , "            # Confidence: inverse of normalized uncertainty"
  , "            max_uncertainty = 5.0  # kW"
  , "            confidence = max(0, 1.0 - uncertainty / max_uncertainty)"
  , ""
  , "            result = {"
  , "                'drPSetpoints': {str(i): p for i, p in enumerate(p_set)},"
  , "                'drQSetpoints': {str(i): q for i, q in enumerate(q_set)},"
  , "                'drUncertainty': uncertainty,"
  , "                'drConfidence': confidence"
  , "            }"
  , "            conn.send((json.dumps(result) + '\\n').encode())"
  , ""
  , "        except Exception as e:"
  , "            error_result = {'error': str(e), 'drPSetpoints': {}, 'drQSetpoints': {},"
  , "                           'drUncertainty': 999.0, 'drConfidence': 0.0}"
  , "            conn.send((json.dumps(error_result) + '\\n').encode())"
  , ""
  , "    conn.close()"
  , "    server.close()"
  , "    os.remove(socket_path)"
  , ""
  , "if __name__ == '__main__':"
  , "    main()"
  ]

-- | Validation result
data ValidationResult = ValidationResult
  { vrAcceptable  :: Bool
  , vrPError      :: Double   -- ^ P setpoint RMSE (kW)
  , vrQError      :: Double   -- ^ Q setpoint RMSE (kVAR)
  , vrTotalError  :: Double
  } deriving (Show, Eq, Generic, NFData, ToJSON, FromJSON)

-- | Validate dispatch result against IPOPT solver
validateDispatch :: ACProblem -> DispatchResult -> IO ValidationResult
validateDispatch prob result = do
  optSol <- solveACOPF prob
  case optSol of
    Nothing -> return ValidationResult
      { vrAcceptable = False
      , vrPError = 1e6
      , vrQError = 1e6
      , vrTotalError = 1e6
      }
    Just sol -> do
      let optP = odPSetpoints (solDispatch sol)
          optQ = odQSetpoints (solDispatch sol)
          predP = drPSetpoints result
          predQ = drQSetpoints result

          pErrors = [abs (Map.findWithDefault 0 k optP - Map.findWithDefault 0 k predP)
                    | k <- Map.keys optP]
          qErrors = [abs (Map.findWithDefault 0 k optQ - Map.findWithDefault 0 k predQ)
                    | k <- Map.keys optQ]

          pRMSE = sqrt $ mean [e^(2::Int) | e <- pErrors]
          qRMSE = sqrt $ mean [e^(2::Int) | e <- qErrors]

          -- Acceptable: P within 0.5 kW, Q within 0.2 kVAR
          acceptable = pRMSE < 0.5 && qRMSE < 0.2

      return ValidationResult
        { vrAcceptable = acceptable
        , vrPError = pRMSE
        , vrQError = qRMSE
        , vrTotalError = pRMSE + qRMSE * 2  -- Weight Q errors
        }
  where
    mean [] = 0
    mean xs = sum xs / fromIntegral (length xs)

-- Helper for socket path
removeFile :: FilePath -> IO ()
removeFile path = do
  _ <- try (System.IO.openFile path System.IO.ReadMode >>= System.IO.hClose) :: IO (Either SomeException ())
  _ <- try (System.Process.callProcess "rm" ["-f", path]) :: IO (Either SomeException ())
  return ()

#else

-- GHCJS stub
import GHC.Generics
import Data.Aeson
import Control.DeepSeq (NFData)
import qualified Data.Map.Strict as Map

data DispatchResult = DispatchResult
  { drPSetpoints :: Map.Map String Double
  , drQSetpoints :: Map.Map String Double
  , drUncertainty :: Double
  , drConfidence :: Double
  } deriving (Show, Eq, Generic, NFData, FromJSON, ToJSON)

data DispatchNet = DispatchNet
  { dnModelPath :: FilePath
  , dnNumNodes :: Int
  , dnNumPVNodes :: Int
  , dnMCSamples :: Int
  } deriving (Show, Eq, Generic, NFData)

data InferenceServer = InferenceServer
data ValidationResult = ValidationResult
  { vrAcceptable :: Bool
  , vrPError :: Double
  , vrQError :: Double
  , vrTotalError :: Double
  } deriving (Show, Eq, Generic, NFData, ToJSON, FromJSON)

startInferenceServer :: DispatchNet -> IO InferenceServer
startInferenceServer _ = error "Not available in GHCJS"
stopInferenceServer :: InferenceServer -> IO ()
stopInferenceServer _ = return ()
withInferenceServer :: DispatchNet -> (InferenceServer -> IO a) -> IO a
withInferenceServer _ _ = error "Not available in GHCJS"
dispatch :: InferenceServer -> Double -> [Double] -> [Double] -> [Double] -> IO DispatchResult
dispatch _ _ _ _ _ = error "Not available in GHCJS"
dispatchWithUncertainty :: InferenceServer -> Double -> [Double] -> [Double] -> [Double] -> Bool -> IO DispatchResult
dispatchWithUncertainty _ _ _ _ _ _ = error "Not available in GHCJS"
validateDispatch :: a -> DispatchResult -> IO ValidationResult
validateDispatch _ _ = error "Not available in GHCJS"

#endif
