{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE NamedFieldPuns #-}
module Chopaan.Node.NodeSensors (power) where

import qualified Prelude as P

import qualified Proto.NodeMessageSchema.NodeMessages as NM
import qualified Proto.NodeMessageSchema.NodeMessages_Fields as NM

import Data.Monoid

import GHC.Generics hiding (C, R)

import Numeric.Units.Dimensional.Prelude

-- Conversions and Accessors
import Data.Time
import Data.Time.Clock.POSIX (posixSecondsToUTCTime)
import Lens.Micro

import Streamly
import qualified Streamly.Prelude as S
import qualified Streamly.Data.Fold as FL

import Control.Monad.Bayes.Class
import Control.Monad.Bayes.Sampler

import Unsafe.Coerce



type R = Double

type Sec s = Quantity DTime s
type I s = ElectricCurrent s
type V s = ElectricPotential s

v :: (Num s) => s -> V s
v = (*~ volt)

i :: (Num s) => s -> I s
i = (*~ ampere)

s :: (Num s) => s -> Sec s
s = (*~ second)

p :: (Num s) => Current s -> Voltage s -> Power s
p (Current i) (Voltage v) = i * v

e :: (Num s) => Power s -> Sec s -> Energy s
e = (*)


type St u v = forall t m. (IsStream t, Monad m) => t m (u v)

toDist :: forall m a. (MonadSample m, Double ~ a) => (a, a) -> a -> m a
toDist (mean, std) a = do
  noise <- normal mean std
  return $ a P.+ noise
  

-- Streams of Sensors
type V' s = St Voltage s
type I' s = St Current s
type P' s = St Power s
type E' s = St Energy s

type Vt t s = V' (t, s)
type It t s = I' (t, s)
type Pt t s = P' (t, s)
type Et t s = E' (t, s)

time :: (Num s) => s -> Sec s
time = s

volts :: (Num s) => s -> Voltage s
volts = Voltage . v

amps :: (Num s) => s -> Current s
amps = Current . i

power :: (Num s) => I' s -> V' s -> P' s
power i v = S.zipWith p i v


--energy :: (Num s) => P' s -> E' s
--energy = S.postscan (FL.sum P.* FL.product) 

newtype Voltage s = Voltage (V s) deriving (Eq, Ord, Show, Generic)
newtype Current s = Current (I s) deriving (Eq, Ord, Show, Generic)

data NodeSensors s = NodeSensors
  { batteryVoltage :: !(V s)
  , gridVoltage :: !(V s)
  , loadCurrent :: !(I s)
  , gridCurrent :: !(I s)
  , genCurrent :: !(I s)
  , temperature :: !s
  } deriving (Eq, Ord, Show, Generic)

getBuses :: NodeSensors s -> IO ()
getBuses = undefined

newtype NodeAt  s = NodeAt (UTCTime, NodeSensors s) deriving (Eq, Ord, Show, Generic)


-- $ converts an EnergyState autogenerated from a protobuf to a NodeSensors that we control
-- $ Incoming current is negative, outgoing is positive
fromNodeMessage :: NM.EnergyState -> NodeAt R
fromNodeMessage nm = NodeAt (nodeTimeToUTC nm, NodeSensors
                       { batteryVoltage = v $ nm ^. NM.batteryVoltage
                       , gridVoltage = v $ nm ^.  NM.gridVoltage
                       , loadCurrent = i $ nm ^.  NM.batteryToLoadCurrent
                       , gridCurrent = cOut + cIn
                       , genCurrent = i $ nm ^. NM.solarInputCurrent
                       , temperature = nm ^. NM.temperature
                       })
  where
    cOut :: I R
    cOut = i $ nm ^.  NM.batteryToGridCurrent
    cIn :: I R
    cIn = i $ (-1) P.* (nm ^. NM.gridToBatteryCurrent)


{--------------------------------------------------------------------------------------------
                                   Units
--------------------------------------------------------------------------------------------}

-- $ converts the millisecond timestamp in the EnergyState to a UTITime  
nodeTimeToUTC :: NM.EnergyState -> UTCTime
nodeTimeToUTC es = posixSecondsToUTCTime $ (fromIntegral $ (es ^. NM.cpuTime))

diffUTC :: forall s. (Fractional s) => UTCTime -> UTCTime -> Sec s
diffUTC a b = s . realToFrac $ diffUTCTime a b


newtype Terminal s = Terminal (Voltage s, Current s) deriving (Eq, Ord, Show, Generic)

data Bus' s = Gen (Terminal s)
           | Storage (Terminal s)
           | TxIn (Terminal s)
           | TxOut (Terminal s)
           | Load (Terminal s)
           deriving (Eq, Ord, Show, Generic) 
{--
data Bus a b where
  B2G :: s -> s -> (Bus Gen (Terminal s) (Storage (Terminal s)))
  G2B :: s -> s -> (Bus Gen)
--}
{--
type LocatedSensor u = (SensorLoc, u)

--newtype Sensor s = Sensor { unSensor :: (I s, V s) }

powerAt :: (Num s) => Sensor s -> Power s
powerAt = (uncurry p) . unSensor

txPower :: (Num s) => NodeSensors s -> LocatedSensor (Power s)
txPower NodeSensors{gridCurrent, gridVoltage} = (TransmitterTerminal, p gridCurrent gridVoltage)

genPower :: (Num s) => NodeSensors s -> LocatedSensor (Power s)
genPower NodeSensors{genCurrent, batteryVoltage} = (BatteryTerminal, p genCurrent batteryVoltage)

loadPower :: (Num s) => NodeSensors s -> LocatedSensor (Power s)
loadPower NodeSensors{loadCurrent, batteryVoltage} = (BatteryTerminal, p loadCurrent batteryVoltage)

batteryCurrent :: Num s => NodeSensors s -> I s
batteryCurrent NodeSensors{gridCurrent, genCurrent, loadCurrent} = gridCurrent + genCurrent - loadCurrent

deltaT :: (Fractional s) => NodeAt s -> NodeAt s -> Sec s
deltaT (NodeAt(t, _)) (NodeAt(t', _)) = diffUTC t t'
--}
