{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE NamedFieldPuns #-}
module Chopaan.Node.NodeSensors (fromNodeMessage, NodeSensors, Power) where

import qualified Prelude as P

import qualified Proto.NodeMessageSchema.NodeMessages as NM
import qualified Proto.NodeMessageSchema.NodeMessages_Fields as NM

import GHC.Generics hiding (C, R)

import Numeric.Units.Dimensional.Prelude

-- Conversions and Accessors
import Data.Time
import Data.Time.Clock.POSIX (posixSecondsToUTCTime)
import Lens.Micro

-- Persistence
--import PostgreSQL.Simple.


type R = Double

type Sec s = Quantity DTime s
type I s = ElectricCurrent s
type V s = ElectricPotential s

v :: (Num s) => s -> V s
v = (*~ volt)

i :: (Num s) => s -> I s
i = (*~ ampere)

s :: (Num s) => s -> Sec s
s = (*~ second)

p :: (Num s) => I s -> V s -> Power s
p = (*)

e :: (Num s) => Power s -> Sec s -> Energy s
e = (*)


data NodeSensors s = NodeSensors
  { batteryVoltage :: !(V s)
  , gridVoltage :: !(V s)
  , loadCurrent :: !(I s)
  , gridCurrent :: !(I s)
  , genCurrent :: !(I s)
  , temperature :: !s
  } deriving (Eq, Ord, Show, Generic)


newtype NodeAt  s = NodeAt (UTCTime, NodeSensors s) deriving (Eq, Ord, Show, Generic)


-- $ converts an EnergyState autogenerated from a protobuf to a NodeSensors that we control
-- $ Incoming current is negative, outgoing is positive
fromNodeMessage :: NM.EnergyState -> NodeAt R
fromNodeMessage nm = NodeAt (nodeTimeToUTC nm, NodeSensors
                       { batteryVoltage = v $ nm ^. NM.batteryVoltage
                       , gridVoltage = v $ nm ^.  NM.gridVoltage
                       , loadCurrent = i $ nm ^.  NM.batteryToLoadCurrent
                       , gridCurrent = cOut + cIn
                       , genCurrent = i $ nm ^. NM.solarInputCurrent
                       , temperature = nm ^. NM.temperature
                       })
  where
    cOut :: I R
    cOut = i $ nm ^.  NM.batteryToGridCurrent
    cIn :: I R
    cIn = i $ (-1) P.* (nm ^. NM.gridToBatteryCurrent)


{--------------------------------------------------------------------------------------------
                                   Units
--------------------------------------------------------------------------------------------}

-- $ converts the millisecond timestamp in the EnergyState to a UTITime  
nodeTimeToUTC :: NM.EnergyState -> UTCTime
nodeTimeToUTC es = posixSecondsToUTCTime $ (fromIntegral $ (es ^. NM.cpuTime))

diffUTC :: forall s. (Fractional s) => UTCTime -> UTCTime -> Sec s
diffUTC a b = s . realToFrac $ diffUTCTime a b


data SensorLoc = BatteryTerminal | TransmitterTerminal

type LocatedSensor u = (SensorLoc, u)

newtype Sensor s = Sensor { unSensor :: (I s, V s) }

powerAt :: (Num s) => Sensor s -> Power s
powerAt = (uncurry p) . unSensor

txPower :: (Num s) => NodeSensors s -> LocatedSensor (Power s)
txPower NodeSensors{gridCurrent, gridVoltage} = (TransmitterTerminal, p gridCurrent gridVoltage)

genPower :: (Num s) => NodeSensors s -> LocatedSensor (Power s)
genPower NodeSensors{genCurrent, batteryVoltage} = (BatteryTerminal, p genCurrent batteryVoltage)

loadPower :: (Num s) => NodeSensors s -> LocatedSensor (Power s)
loadPower NodeSensors{loadCurrent, batteryVoltage} = (BatteryTerminal, p loadCurrent batteryVoltage)

batteryCurrent :: Num s => NodeSensors s -> I s
batteryCurrent NodeSensors{gridCurrent, genCurrent, loadCurrent} = gridCurrent + genCurrent - loadCurrent

deltaT :: (Fractional s) => NodeAt s -> NodeAt s -> Sec s
deltaT (NodeAt(t, _)) (NodeAt(t', _)) = diffUTC t t'
