name: Build Chopaan
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_version: 2.4
          nix_conf: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org s3://ee-nixcache?region=ap-southeast-1 https://hydra.iohk.io https://iohk.cachix.org https://nixcache.reflex-frp.org https://nixfmt.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ee-nixcache:qydUr3bm5mYfgWQDJn6S0VZGzGDZ5uwvzhEFlQVshDk= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= nixfmt.cachix.org-1:uyEQg16IhCFeDpFV07aL+Dbmh18XHVUqpkk/35WAgJI=
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NIX_BUCKET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NIX_BUCKET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: build
        run: nix build .
        
